---
- name: apparmor | disabling apparmor profiles for libvirt
  file:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    state: link
  become: true
  notify: "reload apparmor profiles"
  with_items:
    - src: /etc/apparmor.d/usr.sbin.libvirtd
      dest: /etc/apparmor.d/disable/usr.sbin.libvirtd
    - src: /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper
      dest: /etc/apparmor.d/disable/usr.lib.libvirt.virt-aa-helper
